//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MengajiOneToOneSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [DisplayName("User Id")]
        [Required(ErrorMessage = "Bahagian ini perlu dilengkapkan")]
        public string a_id { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Bahagian ini perlu dilengkapkan")]
        [DataType(DataType.Password)]
        public string a_password { get; set; }
        public string a_fname { get; set; }
        public string a_lname { get; set; }
        public string a_email { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
