//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MengajiOneToOneSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Package
    {
        public int cp_id { get; set; }
        public string cp_name { get; set; }
        public Nullable<double> cp_fees { get; set; }
    }
}
