//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MengajiOneToOneSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryInvoice
    {
        public int i_id { get; set; }
        public Nullable<double> i_amount { get; set; }
        public string i_status { get; set; }
        public string t_id { get; set; }
        public Nullable<int> i_month { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
