//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MengajiOneToOneSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.ClassRecords = new HashSet<ClassRecord>();
            this.PerformanceReports = new HashSet<PerformanceReport>();
            this.SalaryInvoices = new HashSet<SalaryInvoice>();
        }

        [DisplayName("Teacher ID")]
        [Required(ErrorMessage = "Bahagian ini perlu dilengkapkan")]
        public string t_id { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Bahagian ini perlu dilengkapkan")]
        [DataType(DataType.Password)]
        public string t_password { get; set; }
        public string t_title { get; set; }
        public string t_fname { get; set; }
        public string t_lname { get; set; }
        public Nullable<int> t_contact { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRecord> ClassRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceReport> PerformanceReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryInvoice> SalaryInvoices { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
