//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MengajiOneToOneSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ClassRecords = new HashSet<ClassRecord>();
            this.PerformanceReports = new HashSet<PerformanceReport>();
        }

        [DisplayName("Student ID")]
        [Required(ErrorMessage = "Bahagian ini perlu dilengkapkan")]
        public string u_id { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "Bahagian ini perlu dilengkapkan")]
        [DataType(DataType.Password)]
        public string u_password { get; set; }
        public string u_fname { get; set; }
        public string u_lname { get; set; }
        public string u_address { get; set; }
        public string u_preferredTime { get; set; }
        public string u_package { get; set; }
        public string u_days { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRecord> ClassRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceReport> PerformanceReports { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
